---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[ntpd::default]
    attributes:
