name 'ntpd'
maintainer 'Roger Delph'
maintainer_email 'roger.delph@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures ntpd'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.2.1'
supports 'centos', '>= 6.7'
supports 'redhat', '>= 6.7'
supports 'amazon', '>= 6.7'
